### ISSUE TITLE
Install packages by default in the user's HOME

### ISSUE THREAD

**Issue by gutierri** [mfichman/winbrew#1]
That would make things simpler and the disc clean
Homebrew is do something like this

see https://github.com/ActiveState/appdirs

What do you think?

**Comment by mfichman** [comment]
Sounds like a fine idea to me, and easy to implement. The default install directory is set in config.py. We'd just need to detect and use the user's home directory instead.

**Comment by gutierri** [comment]
@mfichman Yes! Using **appdirs** solve? Or rather do without this dependency?

**Comment by mfichman** [comment]
I think os.environ['APPDIR'] might work ;)

It'd be great not to add the dependency if not necessary!

Matt

**Comment by gutierri** [comment]
@mfichman Good! I will take time to try to see it :)
