### ISSUE TITLE
add alias 'brew'

### ISSUE THREAD

**Issue by gutierri** [mfichman/winbrew#3]
Add 'brew' on setup.py equal to pull winbrew, it looks good? (ref https://github.com/mfichman/winbrew/blob/master/setup.py#L15)

**Comment by mfichman** [comment]
I think this is probably OK, since nothing else uses the `brew` command on Windows. 

My only hesitation is that `winbrew` has different command-line syntax than `brew` on OS X, so people might run into errors if they try to use `winbrew` as an exact/compatible substitute for `brew.` 

Thoughts?

**Comment by gutierri** [comment]
; / It makes sense to think so. But a way to avoid this problem is to make clear the 'README' incompatibility.

We can add alias 'brew' and keep the 'winbrew' explicit in the documentation and elsewhere. Alias 'brew' is only one alternative.

**Comment by mfichman** [comment]
Sure, sounds good to me. If you'd like to make the change, go ahead and do so. Otherwise, I will commit the change after Christmas :)

**Comment by gutierri** [comment]
Close?

**Comment by mfichman** [comment]
Yes, thanks!
